import { KeyRound, Save, UserRound } from "lucide-react";
import type { FormEvent } from "react";
import type { StudentProfile } from "../types/auth";

export function SettingsPage({ profile, loading, onName, onPassword }: { profile: StudentProfile; loading: boolean; onName: (firstName: string, lastName: string) => void; onPassword: (currentPassword: string, newPassword: string, confirm: string, form: HTMLFormElement) => void }) {
  const name = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onName(String(data.get("firstName")), String(data.get("lastName"))); };
  const password = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onPassword(String(data.get("currentPassword")), String(data.get("newPassword")), String(data.get("confirmPassword")), event.currentTarget); };
  return <div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]">
    <aside><span className="grid size-11 place-items-center rounded-lg bg-[#dff1ea] text-[#176b55]"><UserRound /></span><h2 className="mt-4 text-lg font-bold">ข้อมูลของฉัน</h2><p className="mt-2 max-w-xs text-xs leading-6 text-[#71847d]">ชื่อของคุณจะปรากฏในหน้าทำข้อสอบและรายงานผล ส่วนอีเมลใช้สำหรับเข้าสู่ระบบ</p><div className="mt-5 border-l-2 border-[#f5c94a] pl-4"><b className="block text-xs">{profile.organization.name}</b><span className="mt-1 block text-[11px] text-[#71847d]">รหัสนักเรียน {profile.studentProfile?.studentCode || "-"}</span></div></aside>
    <div className="divide-y divide-[#dce7e2] rounded-lg border border-[#dce7e2] bg-white px-5 sm:px-7"><form className="py-6" onSubmit={name}><header><h3 className="font-bold">ชื่อที่แสดง</h3><p className="mt-1 text-[11px] text-[#879890]">แก้ไขชื่อและนามสกุลของคุณ</p></header><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="ชื่อ" name="firstName" defaultValue={profile.firstName} /><Field label="นามสกุล" name="lastName" defaultValue={profile.lastName} /></div><label className="mt-4 block text-xs font-semibold text-[#526a62]">อีเมล<input className="student-input mt-2 bg-[#f5f8f6]" value={profile.email} disabled /></label><button className="student-button-primary mt-5" disabled={loading}><Save size={16} />บันทึกชื่อ</button></form>
      <form className="py-6" onSubmit={password}><header className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#fff0c8] text-[#805e10]"><KeyRound size={18} /></span><div><h3 className="font-bold">เปลี่ยนรหัสผ่าน</h3><p className="mt-1 text-[11px] text-[#879890]">ใช้รหัสผ่านอย่างน้อย 8 ตัวอักษร</p></div></header><div className="mt-5 grid gap-4"><Field label="รหัสผ่านปัจจุบัน" name="currentPassword" type="password" minLength={8} /><div className="grid gap-4 sm:grid-cols-2"><Field label="รหัสผ่านใหม่" name="newPassword" type="password" minLength={8} /><Field label="ยืนยันรหัสผ่านใหม่" name="confirmPassword" type="password" minLength={8} /></div></div><button className="student-button-primary mt-5" disabled={loading}><KeyRound size={16} />เปลี่ยนรหัสผ่าน</button></form></div>
  </div>;
}

function Field(props: { label: string; name: string; defaultValue?: string; type?: string; minLength?: number }) { return <label className="block text-xs font-semibold text-[#526a62]">{props.label}<input className="student-input mt-2" required {...props} /></label>; }
